// Generated user unit that supervises the host lifecycle entry point (spec #10 "Health and Lifecycle").
// generateUnit is pure; writeUnitAtomic writes it with a temporary sibling, fsync and rename. The installer (#16)
// calls the same functions. No [Install] section: the unit cannot be enabled, so it never starts at login.
import { closeSync, fsyncSync, mkdirSync, openSync, readFileSync, renameSync, rmSync, writeSync } from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import { CliError } from "./errors.js";

export const DEFAULT_UNIT = "storybench.service";
const UNIT_NAME = /^[A-Za-z0-9][A-Za-z0-9_.@-]{0,120}\.service$/;

export function unitName(env = process.env) {
  const value = env.STORYBENCH_UNIT_NAME || DEFAULT_UNIT;
  if (!UNIT_NAME.test(value)) throw new CliError("STORYBENCH_UNIT_NAME must be a plain systemd service name ending in .service");
  return value;
}

function checkValue(value, label) {
  if (typeof value !== "string" || !value) throw new CliError(`${label} is required for the service unit`);
  if (/[\u0000-\u001f\u007f]/.test(value)) throw new CliError(`${label} contains control characters and cannot be used in a service unit`);
  return value;
}
function checkPath(value, label) {
  checkValue(value, label);
  if (!path.isAbsolute(value) || path.normalize(value) !== value) throw new CliError(`${label} must be a normalized absolute path`);
  return value;
}

// systemd command-line quoting: double quotes with \ and " escaped; % (specifiers) doubled; $ (variables) doubled.
export function quoteArg(value) {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/%/g, "%%").replace(/\$/g, "$$$$")}"`;
}
// Single-value path settings (WorkingDirectory=) take no quotes; specifiers are still expanded, so escape %.
const plainPath = (value) => value.replace(/%/g, "%%");

export function generateUnit({ node, hostEntry, hostConfig, workingDirectory, stopTimeoutS = 90, environment = {}, description = "Storybench local service" }) {
  checkPath(node, "The Node.js executable");
  checkPath(hostEntry, "The host entry point");
  checkPath(hostConfig, "The host configuration");
  checkPath(workingDirectory, "The release directory");
  if (/^\s|\s$/.test(workingDirectory)) throw new CliError("The release directory must not start or end with whitespace");
  if (!Number.isInteger(stopTimeoutS) || stopTimeoutS < 10 || stopTimeoutS > 900) throw new CliError("The stop timeout must be 10-900 seconds");
  const env = Object.entries(environment).map(([key, value]) => {
    if (!/^[A-Z_][A-Z0-9_]*$/.test(key)) throw new CliError(`Invalid environment name ${key}`);
    return `Environment=${quoteArg(`${key}=${checkValue(value, key)}`)}`;
  });
  return [
    "# Generated by storybench. Changes are overwritten by `storybench up`.",
    "[Unit]",
    `Description=${checkValue(description, "Description").replace(/%/g, "%%")}`,
    "After=docker.service",
    // Bounded restarts: at most 3 automatic restarts in 5 minutes, then the unit stays failed.
    "StartLimitIntervalSec=300",
    "StartLimitBurst=3",
    "",
    "[Service]",
    "Type=simple",
    `WorkingDirectory=${plainPath(workingDirectory)}`,
    `ExecStart=${[node, hostEntry, "--config", hostConfig].map(quoteArg).join(" ")}`,
    ...env,
    "Restart=on-failure",
    "RestartSec=5",
    // The host drains on SIGTERM (app stop, workers with descendants, confirmation); give it time before SIGKILL.
    "KillSignal=SIGTERM",
    "KillMode=mixed",
    `TimeoutStopSec=${stopTimeoutS}`,
    "UMask=0077",
    "",
  ].join("\n");
}

export function readUnit(file) {
  try { return readFileSync(file, "utf8"); } catch (error) { if (error.code === "ENOENT") return null; throw error; }
}

// Returns true when the file changed (the caller then reloads the user manager).
export function writeUnitAtomic(file, content) {
  if (readUnit(file) === content) return false;
  const directory = path.dirname(file);
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  const temporary = path.join(directory, `.${path.basename(file)}.${process.pid}.${crypto.randomUUID()}.tmp`);
  const descriptor = openSync(temporary, "wx", 0o644);
  try { writeSync(descriptor, content); fsyncSync(descriptor); }
  catch (error) { closeSync(descriptor); rmSync(temporary, { force: true }); throw error; }
  closeSync(descriptor);
  renameSync(temporary, file);
  const handle = openSync(directory, "r");
  try { fsyncSync(handle); } finally { closeSync(handle); }
  return true;
}
